name: cdn_publish

on:
  push:
    branches:
      - master
  pull_request:
    types: [opened,reopened,edited,synchronize]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [ 14.x ]
    steps:
      - name: checkout master
        uses: actions/checkout@master

      - name: setup node ${{ matrix.node-version }}
        uses: actions/setup-node@master
        with:
          node-version: ${{ matrix.node-version }}

      - name: restore cached node_modules
        uses: actions/cache@v1
        with:
          path: node_modules
          key: ${{ runner.os }}-cached-node-modules-${{ hashFiles('**/package-lock.json') }}

      - name: install dependencies
        if: steps.cache.outputs.cache-hit != 'true'
        run: npm install

      - name: generate dist files
        run: npm run build

      - name: Upload COS
        uses: zkqiang/tencent-cos-action@v0.1.0
        with:
          args: delete -r -f / && upload -r ./dist/ /
          secret_id: ${{ secrets.SECRET_ID }}
          secret_key: ${{ secrets.SECRET_KEY }}
          bucket: ${{ secrets.BUCKET }}
          region: ap-guangzhou
